version: '3.9'
services:
  db:
    image: fiartag/poststartupmoneymgm:latest
    ports:
      - "5432:5432"
    container_name: postgresql_container
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=Bgl862304*
      - POSTGRES_USER=postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: fiartag/moneymanagment-backend:latest
    container_name: moneymanagment_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Bgl862304*
    depends_on:
      db:
        condition: service_healthy
    restart: always
