spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mgmtest
    username: postgres
    password: Bgl862304*
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  logging:
    level:
      org.hibernate: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#spring:
#  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#      hibernate:
#        ddl-auto: update
#      database-platform: org.hibernate.dialect.PostgreSQLDialect
#      show-sql: true
#      properties:
#        hibernate:
#          format_sql: true
#  mvc:
#      throw-exception-if-no-handler-found: true
#  web:
#      resources:
#        add-mappings: false
#  logging:
#      level:
#        org.springframework.security: DEBUG
#        org.springframework.web.cors: TRACE
#        org.hibernate: DEBUG
#        org.hibernate.SQL: DEBUG
#        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
